name: "Continuous Integration"

on:
  push:

jobs:
  build:

    name: Run route queries
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '14'

      - name: Run queries
        run: |
          ./gradlew run
